# Generated by Django 6.0.4 on 2026-04-29 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('user_a_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user_b_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('room_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', '進行中'), ('closed', '已結束'), ('cancelled', '已取消')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_matches_as_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('stance_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stance_category', models.CharField(choices=[('support', '支持'), ('neutral', '中立'), ('oppose', '反對')], db_index=True, max_length=20)),
                ('survey_answers', models.JSONField(default=dict)),
                ('survey_open_answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stance_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('stance_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('matching', '匹配中'), ('matched', '匹配成功'), ('cancelled', '取消匹配')], db_index=True, default='matching', max_length=20)),
                ('waiting_started_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='api.dialoguematch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='api.userstanceprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dialoguematch',
            constraint=models.CheckConstraint(condition=models.Q(('user_a', models.F('user_b')), _negated=True), name='match_users_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='dialoguematch',
            constraint=models.CheckConstraint(condition=models.Q(('user_a_score__gte', 1), ('user_a_score__lte', 7)), name='match_user_a_score_between_1_and_7'),
        ),
        migrations.AddConstraint(
            model_name='dialoguematch',
            constraint=models.CheckConstraint(condition=models.Q(('user_b_score__gte', 1), ('user_b_score__lte', 7)), name='match_user_b_score_between_1_and_7'),
        ),
        migrations.AddConstraint(
            model_name='userstanceprofile',
            constraint=models.UniqueConstraint(fields=('user', 'topic_id'), name='uniq_stance_profile_user_topic'),
        ),
        migrations.AddConstraint(
            model_name='userstanceprofile',
            constraint=models.CheckConstraint(condition=models.Q(('stance_score__gte', 1), ('stance_score__lte', 7)), name='stance_score_between_1_and_7'),
        ),
        migrations.AddIndex(
            model_name='matchqueueentry',
            index=models.Index(fields=['topic_id', 'status', 'stance_score'], name='match_queue_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchqueueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'matching')), fields=('user', 'topic_id'), name='uniq_active_queue_user_topic'),
        ),
        migrations.AddConstraint(
            model_name='matchqueueentry',
            constraint=models.CheckConstraint(condition=models.Q(('stance_score__gte', 1), ('stance_score__lte', 7)), name='queue_stance_score_between_1_and_7'),
        ),
    ]
