# Generated by Django 6.0.4 on 2026-05-05 18:37

import pgvector.django.vector
from django.db import migrations, models


def enable_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('CREATE EXTENSION IF NOT EXISTS vector')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aiconversation_dialogue_phase_and_more'),
    ]

    operations = [
        migrations.RunPython(enable_vector_extension, migrations.RunPython.noop),
        migrations.AddField(
            model_name='dialoguematch',
            name='likert_distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dialoguematch',
            name='match_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dialoguematch',
            name='matching_algorithm_version',
            field=models.CharField(default='legacy', max_length=64),
        ),
        migrations.AddField(
            model_name='dialoguematch',
            name='semantic_distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='userstanceprofile',
            name='q9_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
