# Generated by Django 6.0.4 on 2026-05-18 02:57

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dialoguematch_likert_distance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguematch',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialoguematch',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialoguematch',
            name='topic_anchor_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='matchmessage',
            name='dialogue_phase',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='matchmessage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='matchmessage',
            name='emotion_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchAISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rephrase', '改述'), ('direction', '引導方向'), ('redirect', '回到主題')], max_length=20)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('suggested_content', models.TextField()),
                ('user_action', models.CharField(blank=True, choices=[('accept', '接受'), ('modify', '修改'), ('ignore', '忽略')], max_length=10, null=True)),
                ('modified_content', models.TextField(blank=True, null=True)),
                ('final_content', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('trigger_score', models.FloatField(blank=True, null=True)),
                ('context_message_ids', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='api.dialoguematch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['match', 'user', 'created_at'], name='match_ai_suggestion_lookup_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchStanceDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift_value', models.FloatField()),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stance_drifts', to='api.dialoguematch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stance_drifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['measured_at'],
                'indexes': [models.Index(fields=['match', 'user', 'measured_at'], name='match_stance_drift_lookup_idx')],
            },
        ),
    ]
