# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_dialoguematch_stats_dialoguematch_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogueSessionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("topic_id", models.PositiveIntegerField(db_index=True)),
                ("topic_title", models.CharField(max_length=255)),
                ("collection_name", models.CharField(max_length=255)),
                ("survey_context", models.JSONField(blank=True, default=dict)),
                ("session_state", models.JSONField(blank=True, default=dict)),
                ("semantic_tree_state", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "進行中"), ("closed", "已結束")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_activity_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogue_session_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "topic_id", "status", "last_activity_at"],
                        name="dialogue_session_restore_idx",
                    ),
                ],
            },
        ),
    ]
