# Generated by Django 6.0.4 on 2026-06-03 09:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dialoguesessionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
