# Generated by Django 6.0.4 on 2026-06-23 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aiconversation_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDialogueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('room_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('experiment_condition', models.CharField(choices=[('ai', 'H-AI'), ('hh', 'H-H')], db_index=True, max_length=4)),
                ('post_likert_1', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-1 (pre=Q8, positive)')),
                ('post_likert_2', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-2 (pre=Q5, reverse)')),
                ('post_likert_3', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-3 (pre=Q3, positive)')),
                ('post_likert_4', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-4 (pre=Q7, positive)')),
                ('post_likert_5', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-5 (pre=Q1, positive)')),
                ('post_likert_6', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-6 (pre=Q4, reverse)')),
                ('post_likert_7', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-7 (pre=Q6, reverse)')),
                ('post_likert_8', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C1-8 (pre=Q2, reverse)')),
                ('exp_stance_change_1', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C2-1 主觀立場改變自覺')),
                ('exp_stance_change_2', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C2-2 主觀立場改變自覺')),
                ('exp_quality_1', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C2-3 對話品質感知')),
                ('exp_quality_2', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C2-4 對話品質感知')),
                ('exp_reflection_1', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C2-5 自我反思/元認知')),
                ('exp_reflection_2', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C2-6 自我反思/元認知')),
                ('ccnd_attention', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C3-1 注意力門檻')),
                ('ccnd_awareness', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C3-2 認知差異覺察')),
                ('ccnd_influence', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='C3-3 表達/思考調整')),
                ('opponent_judgment', models.PositiveSmallIntegerField(blank=True, help_text='1=真人, 2=AI, 3=不確定；H-H 組為 NULL', null=True)),
                ('post_open_comprehension', models.TextField(help_text='D1 — 對立觀點陳述（最低 50 字）；與前測 Q10 同題幹，向量化後存 pgvector')),
                ('post_open_feedback', models.TextField(blank=True, help_text='D2 — 自由回饋，無字數限制')),
                ('discomfort_flag', models.BooleanField(default=False)),
                ('consent_confirmed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dialogue_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscomfortReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discomfort_report', to='api.postdialogueresponse')),
            ],
        ),
        migrations.AddIndex(
            model_name='postdialogueresponse',
            index=models.Index(fields=['user', 'topic_id', 'created_at'], name='post_response_user_topic_idx'),
        ),
        migrations.AddConstraint(
            model_name='postdialogueresponse',
            constraint=models.CheckConstraint(condition=models.Q(('opponent_judgment__isnull', True), ('opponent_judgment__in', [1, 2, 3]), _connector='OR'), name='post_opponent_judgment_valid'),
        ),
    ]
