# Generated by Django 6.0.4 on 2026-06-29 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_dialogue_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ux_matching', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='F1 配對機制')),
                ('ux_chatroom', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='F2 對話室體驗')),
                ('ux_nlp_intervention', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='F3 NLP 介入機制')),
                ('ux_ccnd', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='F4 概念認知網路圖')),
                ('ux_overall', models.PositiveSmallIntegerField(help_text='1–7 Likert scale', verbose_name='F5 系統整體可用性')),
                ('nps_score', models.PositiveSmallIntegerField(help_text='F6 推薦意願 0–10')),
                ('ux_improvement', models.TextField(blank=True, help_text='F7 最需要改進的地方（選填）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_feedback', to='api.postdialogueresponse')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('nps_score__gte', 0), ('nps_score__lte', 10)), name='platform_feedback_nps_0_10')],
            },
        ),
    ]
