# Generated by Django 6.0.4 on 2026-07-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_issue'),
        ('api', '0010_platformfeedback'),
    ]

    operations = [
    ]
