# Generated by Django 6.0.4 on 2026-07-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_0009_issue_0010_platformfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
