# Generated by Django 6.0.4 on 2026-07-12 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_0009_issue_0010_platformfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCNDTimelineUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ai', 'H-AI'), ('match', 'H-H')], max_length=8)),
                ('conversation_id', models.CharField(db_index=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='核准解鎖的研究者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccnd_timeline_unlocks_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='被解鎖的受試者', on_delete=django.db.models.deletion.CASCADE, related_name='ccnd_timeline_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'conversation_id'), name='uniq_ccnd_timeline_unlock')],
            },
        ),
    ]
