# Generated by Django 6.0.4 on 2026-07-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ccndtimelineunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdialogueresponse',
            name='delta_s_value',
            field=models.FloatField(blank=True, help_text='立場移動量 s_post − s_pre；正=偏支持、負=偏反對', null=True),
        ),
        migrations.AddField(
            model_name='postdialogueresponse',
            name='s_pre',
            field=models.FloatField(blank=True, help_text='前測立場分數快照（1–7）；無前測資料時為 NULL', null=True),
        ),
        migrations.AddField(
            model_name='postdialogueresponse',
            name='stance_centrism_value',
            field=models.FloatField(blank=True, help_text='去極化指標 |s_post−4|−|s_pre−4|；< 0 = 去極化，> 0 = 更極化', null=True),
        ),
    ]
