# Generated by Django 6.0.4 on 2026-07-25 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_postdialogueresponse_delta_s_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('ai', 'AI 回應'), ('match', '配對訊息')], max_length=8)),
                ('target_id', models.BigIntegerField()),
                ('value', models.SmallIntegerField(choices=[(1, '讚'), (-1, '倒讚')])),
                ('topic_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'conversation_id'], name='msg_reaction_conv_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='uniq_message_reaction_user_target'), models.CheckConstraint(condition=models.Q(('value__in', [1, -1])), name='message_reaction_value_like_dislike')],
            },
        ),
    ]
