# Generated by Django 6.0.4 on 2026-07-19 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_title_usertitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='usertitle',
            options={'ordering': ['unlocked_at']},
        ),
        migrations.AddConstraint(
            model_name='usertitle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('user',), name='user_one_selected_title'),
        ),
    ]
