# Generated by Django 6.0.4 on 2026-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='contract_violated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='internal_judgment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='ai_response',
            field=models.TextField(blank=True, help_text='AI 的回覆（僅 <reply> 區塊，已由 ReplyStreamGate 剝離判定段）', null=True),
        ),
    ]
