# Generated by Django 6.0.4 on 2026-07-26 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_close_stale_dialogue_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_entry_mode', models.CharField(choices=[('mixed', '混合入口'), ('split', '分開入口')], default='mixed', help_text='一般使用者看到的入口形式', max_length=16)),
                ('researcher_entry_mode', models.CharField(choices=[('mixed', '混合入口'), ('split', '分開入口')], default='split', help_text='研究者看到的入口形式', max_length=16)),
                ('match_fallback_timeout_minutes', models.PositiveIntegerField(default=5, help_text='配對等待超過這個分鐘數後，詢問使用者要不要改跟 AI 對話')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicDisplayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(unique=True)),
                ('visible_to_participant', models.BooleanField(default=True)),
                ('visible_to_researcher', models.BooleanField(default=True)),
                ('support_threshold', models.FloatField(blank=True, help_text='null＝沿用 SURVEY_CONFIGS 的預設門檻', null=True)),
                ('oppose_threshold', models.FloatField(blank=True, help_text='null＝沿用 SURVEY_CONFIGS 的預設門檻', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
