# Generated by Django 6.0.4 on 2026-07-27 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_platformdisplaysetting_topicdisplayoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueEntryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('route', models.CharField(choices=[('ai', 'AI 對話'), ('match', '真人配對')], db_index=True, max_length=8)),
                ('stance_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stance_category', models.CharField(max_length=20)),
                ('support_threshold', models.FloatField()),
                ('oppose_threshold', models.FloatField()),
                ('entry_mode_at_assignment', models.CharField(max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('fallback_offered_at', models.DateTimeField(blank=True, help_text='第一次被提示可以改跟 AI 對話的時間', null=True)),
                ('fallback_accepted_at', models.DateTimeField(blank=True, help_text='使用者接受改跟 AI 對話的時間', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'topic_id'), name='uniq_entry_assignment_user_topic')],
            },
        ),
    ]
