# Generated by Django 6.0.4 on 2026-07-29 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_godotentryticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dialoguematch',
            name='match_user_a_score_between_1_and_7',
        ),
        migrations.RemoveConstraint(
            model_name='dialoguematch',
            name='match_user_b_score_between_1_and_7',
        ),
        migrations.AlterField(
            model_name='dialoguematch',
            name='user_a_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dialoguematch',
            name='user_b_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddConstraint(
            model_name='dialoguematch',
            constraint=models.CheckConstraint(condition=models.Q(('user_a_score__isnull', True), models.Q(('user_a_score__gte', 1), ('user_a_score__lte', 7)), _connector='OR'), name='match_user_a_score_between_1_and_7'),
        ),
        migrations.AddConstraint(
            model_name='dialoguematch',
            constraint=models.CheckConstraint(condition=models.Q(('user_b_score__isnull', True), models.Q(('user_b_score__gte', 1), ('user_b_score__lte', 7)), _connector='OR'), name='match_user_b_score_between_1_and_7'),
        ),
    ]
