# Generated by Django 6.0.4 on 2026-08-01 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_aiconversation_contract_violated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='ai_turn_is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialoguesessionrecord',
            name='input_attempt_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dialoguesessionrecord',
            name='invalid_input_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dialoguesessionrecord',
            name='invalid_input_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dialoguesessionrecord',
            name='invalid_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialoguesessionrecord',
            name='substantive_turn_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchInputGateStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_input_count', models.IntegerField(default=0)),
                ('invalid_input_total', models.IntegerField(default=0)),
                ('input_attempt_total', models.IntegerField(default=0)),
                ('invalid_ratio', models.FloatField(blank=True, null=True)),
                ('substantive_turn_count', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_gate_stats', to='api.dialoguematch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_input_gate_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'user'), name='uniq_input_gate_stat_match_user')],
            },
        ),
    ]
