# Generated by Django 6.0.4 on 2026-08-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_postdialogueresponse_exp_comprehension_1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('viewpoint', '觀點'), ('video', '影片')], max_length=16)),
                ('target_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'target_type', 'created_at'], name='favorite_user_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='uniq_favorite_user_target')],
            },
        ),
    ]
