# Generated by Django 6.0.4 on 2026-08-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguesessionrecord',
            name='profanity_only_total',
            field=models.IntegerField(default=0),
        ),
    ]
