# Generated by Django 6.0.4 on 2026-08-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_dialoguesessionrecord_profanity_only_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdialogueresponse',
            name='is_superseded',
            field=models.BooleanField(default=False),
        ),
    ]
