# Generated by Django 6.0.4 on 2026-08-19 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_supersede_pre_existing_duplicate_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postdialogueresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superseded', False), ('session_id__isnull', False)), fields=('user', 'session_id'), name='post_response_user_session_unique'),
        ),
        migrations.AddConstraint(
            model_name='postdialogueresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superseded', False), ('room_id__isnull', False)), fields=('user', 'room_id'), name='post_response_user_room_unique'),
        ),
    ]
