# Generated by Django 6.0.4 on 2026-08-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_post_response_unique_per_dialogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdialogueresponse',
            name='post_open_comprehension',
            field=models.TextField(help_text='D1 — 對立觀點陳述（最低 30 字）；與前測 Q10 同題幹，向量化後存 pgvector'),
        ),
    ]
