# Generated by Django 6.0.4 on 2026-08-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_postdialogueresponse_post_open_comprehension'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOpeningBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('directions', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('llm', 'LLM 生成'), ('fallback', '議題錨點 fallback')], default='fallback', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_brief', to='api.dialoguematch')),
            ],
        ),
    ]
