# Generated by Django 6.0.4 on 2026-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_matchopeningbrief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdialogueresponse',
            name='post_open_feedback',
            field=models.TextField(blank=True, help_text='D2 — 自由回饋，選填，無字數限制'),
        ),
    ]
