# Generated by Django 6.0.4 on 2026-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_postdialogueresponse_post_open_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('section', models.CharField(choices=[('hot', '熱門'), ('latest', '最新')], max_length=16)),
                ('rank', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('outline', models.TextField(blank=True)),
                ('url', models.URLField(max_length=500)),
                ('endorse_count', models.PositiveIntegerField(default=0)),
                ('endorse_goal', models.PositiveIntegerField(default=0)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('organizations', models.JSONField(blank=True, default=list)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'rank'],
                'indexes': [models.Index(fields=['section', 'rank'], name='policy_idea_section_rank')],
                'constraints': [models.UniqueConstraint(fields=('section', 'external_id'), name='uniq_policy_idea_section_ext')],
            },
        ),
    ]
