# Generated by Django 6.0.4 on 2026-09-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_stance_profile_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='llm_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
