# Generated by Django 6.0.4 on 2026-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_aiconversation_llm_model_aiconversation_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguesessionrecord',
            name='lit_anchor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchinputgatestat',
            name='lit_anchor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
