# Generated by Django 6.0.4 on 2026-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_lit_anchor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdisplaysetting',
            name='registration_open',
            field=models.BooleanField(default=True, help_text='關閉時 /api/register/ 與註冊前信箱驗證端點一律回 403；研究者代開帳號（/api/accounts/）不受影響'),
        ),
    ]
