# Generated by Django 6.0.4 on 2026-08-18 03:42

from django.db import migrations, models


def blank_email_to_null(apps, schema_editor):
    """既有帳號的 email 全是空字串（研究者代開時沒填）。
    必須先回填成 NULL，之後加 UNIQUE 才不會撞重複值。
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(email="").update(email=None)


def null_email_to_blank(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email__isnull=True).update(email="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_repoint_user_content_type'),
    ]

    # 順序是三步，不能簡化成兩步：
    #   1. 先讓欄位可為 NULL —— RunPython 要寫 NULL 進去，欄位得先允許。
    #      這一步還不能加 UNIQUE：既有帳號的 email 全是空字串，會互相相撞。
    #   2. 空字串回填成 NULL。
    #   3. 沒有重複值了，這時才加得上 UNIQUE。
    #
    # 這個順序在全新資料庫上看不出差別（零筆資料，RunPython 是 no-op），
    # 只有在既有資料庫上才會顯現。見 tests_email_backfill_migration.py。
    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="email address",
            ),
        ),
        migrations.RunPython(blank_email_to_null, null_email_to_blank),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_research_subject",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
