# Generated by Django 6.0.4 on 2026-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
