TOPIC_CONFIGS = {
    102: {
        "title": "台灣核能議題討論",
        "topic_description": "台灣是否應重啟核電廠以應對能源轉型與減碳需求",
        "collection_name": "nuclear_energy_all",
        "off_topic_detection": {
            "anchor_text": "台灣是否應該擴大發展核能發電",
            "threshold": 0.35,
            "window_size": 3,
            "min_messages": 2,
        },
        "date": "2026/04/27",
        "display_order": 1,
        "anchors": [
            {"id": "anchor_safety", "name": "核能安全"},
            {"id": "anchor_economy", "name": "經濟成本"},
            {"id": "anchor_energy", "name": "能源問題"},
            {"id": "anchor_environment", "name": "環境保護"},
            {"id": "anchor_governance", "name": "民主治理"},
            {"id": "anchor_waste", "name": "核廢處理"},
        ],
        "anchor_descriptions": {
            "anchor_safety": "事故風險、老舊延役、地震帶、反應爐技術、輻射外洩、安全審查。",
            "anchor_economy": "發電成本、維護成本、除役成本、補貼、電價、投資效益。",
            "anchor_energy": "供電穩定、缺電風險、基載、能源配置、再生能源互補。",
            "anchor_environment": "減碳、空污、生態衝擊、土地使用、氣候風險。",
            "anchor_governance": "資訊公開、民意溝通、政府信任、程序正義、決策透明、主權與責任。",
            "anchor_waste": "核廢料處置、最終儲存、地方承擔、長期管理、處置場風險。",
        },
        "stance_labels": {
            "support": {
                "user_label": "較支持核電",
                "agent_stance": "較反對核電",
                "agent_stance_summary": "認為核電的安全、成本與核廢料風險仍被低估，不應輕率視為能源轉型解方。",
            },
            "oppose": {
                "user_label": "較反對核電",
                "agent_stance": "較支持核電",
                "agent_stance_summary": "認為核電在減碳與穩定供電上仍具必要性，不應過早排除。",
            },
            "neutral": {
                "user_label": "立場中立或尚未明確",
                "agent_stance": "提出相反觀點",
                "agent_stance_summary": "會根據使用者當前的考量重點，補上另一側對安全、成本、環境與供電穩定性的判斷。",
            },
        },
    },
    103: {
        "title": "女性義務兵役討論",
        "topic_description": "台灣是否應將女性納入義務兵役制度",
        "collection_name": "military_service_women_news",
        "off_topic_detection": {
            "anchor_text": "台灣是否應將女性納入義務兵役制度",
            "threshold": 0.25,
            "window_size": 3,
            "min_messages": 2,
        },
        "date": "2026/06/25",
        "display_order": 2,
        # 這 5 個錨點對應本地分類模型（women_conscription_node_model）實際訓練出來的
        # 5 個 macro class（見 ml_models/women_conscription_node_model/class_maps.json）。
        # 模型的 class_id=5「其他」是分類不進任何錨點的雜訊桶，不對應任何錨點，
        # 所以這裡刻意只列 5 個——不是漏了「體能訓練」「個人意願」，是模型訓練時
        # 就沒有把這兩個切成獨立的 macro class（相關內容散落在其他 class 底下或被
        # 分進「其他」），勉強塞回 6 個固定錨點反而會讓其中 2 個永遠是空節點。
        "anchors": [
            {"id": "anchor_equality", "name": "性別平等"},
            {"id": "anchor_defense", "name": "國防戰力"},
            {"id": "anchor_policy", "name": "徵兵制度"},
            {"id": "anchor_military_conditions", "name": "軍中現況"},
            {"id": "anchor_social", "name": "社會影響"},
        ],
        "anchor_descriptions": {
            "anchor_equality": "性別平等原則、權利義務對等、公平正義、歧視與差別待遇。",
            "anchor_defense": "兵源需求、戰力提升、國防安全、戰備整備、募兵成效。",
            "anchor_policy": "國際比較、法律修訂、現行制度、政策可行性、配套措施。",
            "anchor_military_conditions": "女性從軍現況、軍中性騷擾與暴力、義務役役期、軍中生活與文化、從軍案例。",
            "anchor_social": "生育率影響、社會分工、群眾看法、文化觀念、心理衝擊。",
        },
        "stance_labels": {
            "support": {
                "user_label": "較支持女性服義務兵役",
                "agent_stance": "較反對女性服義務兵役",
                "agent_stance_summary": "認為性別生理差異、社會影響等因素，使強制女性服役的必要性與可行性仍有待商榷。",
            },
            "oppose": {
                "user_label": "較反對女性服義務兵役",
                "agent_stance": "較支持女性服義務兵役",
                "agent_stance_summary": "認為基於性別平等原則與國防兵源需求，女性應與男性承擔相同的義務兵役責任。",
            },
            "neutral": {
                "user_label": "立場中立或尚未明確",
                "agent_stance": "提出相反觀點",
                "agent_stance_summary": "會根據使用者當前的考量重點，補上另一側對平等、體能、國防需求或社會影響的判斷。",
            },
        },
    },
}

SURVEY_CONFIGS = {
    102: {
        "topic_id": 102,
        "title": "立場檢測問卷",
        "subtitle": "第一部分會計算核能立場分數；第二部分先保留開放式觀點接口。",
        "scale": {
            "min": 1,
            "max": 7,
            "min_label": "非常不同意",
            "max_label": "非常同意",
        },
        "stance_rules": {
            "reverse_question_ids": [2, 4, 5, 6],
            "support_threshold": 4.5,
            "oppose_threshold": 3.5,
            "neutral_min": 3.5,
            "neutral_max": 4.5,
        },
        "questions": [
            {
                "id": 1,
                "code": "Q1",
                "tag": "安全",
                "question_type": "likert",
                "dimension": "安全",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "我認為台灣現有的核電技術與管理能力，足以確保核電廠的安全運轉。",
            },
            {
                "id": 2,
                "code": "Q2",
                "tag": "環境",
                "question_type": "likert",
                "dimension": "環境",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "核廢料的長期處置風險，使核電不應被視為環保的能源選項。",
            },
            {
                "id": 3,
                "code": "Q3",
                "tag": "經濟",
                "question_type": "likert",
                "dimension": "經濟",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "與其他能源相比，核電在發電成本與供電穩定性上具有明顯優勢。",
            },
            {
                "id": 4,
                "code": "Q4",
                "tag": "替代方案",
                "question_type": "likert",
                "dimension": "替代方案",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "台灣應優先發展再生能源，而非依賴核電來達成淨零碳排目標。",
            },
            {
                "id": 5,
                "code": "Q5",
                "tag": "安全",
                "question_type": "likert",
                "dimension": "安全",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "考量台灣的天然災害，核電廠的存在對周邊居民構成不可接受的威脅。",
            },
            {
                "id": 6,
                "code": "Q6",
                "tag": "經濟",
                "question_type": "likert",
                "dimension": "經濟",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "核電廠的建設、維護與除役成本被嚴重低估，實際上並不划算。",
            },
            {
                "id": 7,
                "code": "Q7",
                "tag": "環境",
                "question_type": "likert",
                "dimension": "環境",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "核電是目前能大規模穩定供電的低碳能源中，最務實可行的選項。",
            },
            {
                "id": 8,
                "code": "Q8",
                "tag": "替代方案",
                "question_type": "likert",
                "dimension": "替代方案",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "在再生能源尚無法滿足基載電力需求的過渡期，核電是必要的橋接方案。",
            },
        ],
        "open_questions": [
            {
                "id": 9,
                "code": "Q9",
                "tag": "核心觀點",
                "question_type": "open_text",
                "text": "請用 3–5 句話說明你對「台灣是否應該使用核電」的看法，以及你最主要的理由。",
                "placeholder": "請用 3–5 句話描述你的觀點與理由",
                "min_sentences": 3,
                "max_sentences": 5,
            },
            {
                "id": 10,
                "code": "Q10",
                "tag": "對立觀點理解",
                "question_type": "open_text",
                "text": "你認為反對（或支持）核電的人，他們最有力的論點是什麼？請試著用他們的角度來陳述。",
                "placeholder": "試著站在對立方角度描述他們最強的論點",
                "min_sentences": 2,
                "max_sentences": 5,
            },
        ],
        "semantic_vector_interface": {
            "enabled": False,
            "status": "pending",
            "target_question_code": "Q9",
            "model_name": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        },
    },
    103: {
        "topic_id": 103,
        "title": "立場檢測問卷",
        "subtitle": "第一部分計算女性兵役立場分數；第二部分為開放式觀點。",
        "scale": {
            "min": 1,
            "max": 7,
            "min_label": "非常不同意",
            "max_label": "非常同意",
        },
        "stance_rules": {
            "reverse_question_ids": [2, 4, 6, 8],
            "support_threshold": 4.5,
            "oppose_threshold": 3.5,
            "neutral_min": 3.5,
            "neutral_max": 4.5,
        },
        "questions": [
            {
                "id": 1,
                "code": "Q1",
                "tag": "平等",
                "question_type": "likert",
                "dimension": "性別平等",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "基於性別平等原則，女性應與男性同樣負有義務兵役責任。",
            },
            {
                "id": 2,
                "code": "Q2",
                "tag": "體能",
                "question_type": "likert",
                "dimension": "體能差異",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "男女生理差異使女性在體能要求上難以勝任一般戰鬥任務。",
            },
            {
                "id": 3,
                "code": "Q3",
                "tag": "國防",
                "question_type": "likert",
                "dimension": "國防戰力",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "讓女性服義務兵役有助於提升國防整體戰力與兵源。",
            },
            {
                "id": 4,
                "code": "Q4",
                "tag": "自願",
                "question_type": "likert",
                "dimension": "自願vs強制",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "在志願役制度下，強制徵召女性並無必要且侵犯個人意願。",
            },
            {
                "id": 5,
                "code": "Q5",
                "tag": "平等",
                "question_type": "likert",
                "dimension": "權利與義務",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "若女性享有與男性相同的社會權利，就應承擔相同的國防義務。",
            },
            {
                "id": 6,
                "code": "Q6",
                "tag": "社會",
                "question_type": "likert",
                "dimension": "社會影響",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "強制徵召女性服役將對家庭結構與生育率產生負面影響。",
            },
            {
                "id": 7,
                "code": "Q7",
                "tag": "國際",
                "question_type": "likert",
                "dimension": "國際比較",
                "direction": "positive",
                "reverse_scored": False,
                "min_value": 1,
                "max_value": 7,
                "text": "許多國家已成功推行性別中立的義務兵役制度，台灣應予以參考。",
            },
            {
                "id": 8,
                "code": "Q8",
                "tag": "替代方案",
                "question_type": "likert",
                "dimension": "替代方案",
                "direction": "reverse",
                "reverse_scored": True,
                "min_value": 1,
                "max_value": 7,
                "text": "現行募兵制若能有效補足兵源，強制女性服役並非必要手段。",
            },
        ],
        "open_questions": [
            {
                "id": 9,
                "code": "Q9",
                "tag": "核心觀點",
                "question_type": "open_text",
                "text": "請用 3–5 句話說明你對「女性是否應服義務兵役」的看法，以及你最主要的理由。",
                "placeholder": "請用 3–5 句話描述你的觀點與理由",
                "min_sentences": 3,
                "max_sentences": 5,
            },
            {
                "id": 10,
                "code": "Q10",
                "tag": "對立觀點理解",
                "question_type": "open_text",
                "text": "你認為反對（或支持）女性服義務兵役的人，他們最有力的論點是什麼？請試著用他們的角度來陳述。",
                "placeholder": "試著站在對立方角度描述他們最強的論點",
                "min_sentences": 2,
                "max_sentences": 5,
            },
        ],
        "semantic_vector_interface": {
            "enabled": False,
            "status": "pending",
            "target_question_code": "Q9",
            "model_name": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        },
    },
}


def get_dialogue_topics() -> list[dict[str, str | int]]:
    topics = []

    for topic_id, config in sorted(
        TOPIC_CONFIGS.items(),
        key=lambda item: item[1].get("display_order", item[0]),
    ):
        topics.append(
            {
                "id": topic_id,
                "title": config["title"],
                "description": config["topic_description"],
                "date": config["date"],
            }
        )

    return topics


def get_dialogue_survey(topic_id: int) -> dict | None:
    return SURVEY_CONFIGS.get(topic_id)
