# -*- coding: utf-8 -*-
"""概念認知網路圖還沒面目全非版

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwNiegKPJa78WRUVBNeIIZTemlPGWb3E

colab狀態安裝ollama並載入gemma3&啟動
"""

#解壓縮工具
!apt-get install -y zstd
#請求連線安裝ollama，以便後續拉gemma3下來
!curl -fsSL https://ollama.ai/install.sh | sh

"""安裝ollama"""

!pip install ollama

"""啟動ollama，準備日誌檔"""

import subprocess
import time

# 在背景啟動 ollama serve
# 我們將輸出導向到 ollama.log 檔案，以免洗版
with open("ollama.log", "w") as f:
    process = subprocess.Popen(["ollama", "serve"], stdout=f, stderr=f)

"""可以拉gemma3:4b了"""

!ollama pull gemma3:4b

import json #輸出可以按照json格式走
import numpy as np
import re
import ollama
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity   #值越大表示越相近

#丟給ollama的資料及格式
def ollama_summary_points(text):
  system_instruction = (
        "你是一個台灣繁體中文的內容分析助手。"
"請針對使用者提供的文本進行重點摘要"
"規則："
"1. 若有重點，請簡短條列，不需做額外證據說明\n"
"2. 若內容無意義、或純屬寒暄，請直接回覆『無重要資訊』，不要寫任何其他字眼。\n"
"3. 每個論點之間請用『$』符號隔開，不要使用數字編號或換行。\n"
  )
  response = ollama.chat(
      model="gemma3:4b",
      messages=[
          {'role': 'system', 'content': system_instruction},
          {'role': 'user', 'content': f"內容如下：\n{text}"}
      ],
      options={'temperature': 0}
  )
  content = response['message']['content'].strip()
  if "無重要資訊" in content:
    return []
  points = [p.strip().replace('*', '').replace("，","<br>") for p in content.split('$') if p.strip()]
  return points
#測試資料
test_data = [
    # 測試 1：【核能轉型 - 多重概念與因果關係】(測試 AI 拆解長句與提煉態度的能力)
    "雖然綠能發電是未來的終極目標，但台灣目前的儲能技術與電網穩定度根本跟不上，貿然廢核只會讓產業面臨隨時斷電的風險。",

    # 測試 2：【核四安檢 - 客觀陳述 + 強烈呼籲】(測試 AI 能否精準抓出具體事物)
    "現在就算核四廠區的設備都還在維護，但安全檢測的報告一直沒有透明公開，民眾對施工品質完全沒信心，台電的對外說明絕對要更誠實。",

    # 測試 3：【能源困境 - 絕望情緒與具體困境融合】(測試 AI 能否輸出帶有情緒的完美短句)
    "電價一直漲實在太誇張，基層家庭連夏天開冷氣都縮衣節食，根本看不到便宜用電的希望，而且核廢料處理遲遲沒有終極方案，真的很無力。",

    # 測試 4：【無具體看法的名詞碎片】(測試防腦補機制：AI 絕對不能幫他造句)
    "至於那個 SMR 小型核反應爐的安全性",

    # 測試 5：【問卷抱怨＋打招呼】(測試無效資訊結界：必須完全濾除)
    "哈囉你好，這份關於能源政策的調查問卷字也太多了吧，看完頭都暈了",

    # 測試 6：【純粹的情緒發洩與無關議題】(測試無效資訊結界)
    "煩死了，家裡冰箱剛好壞掉害我心情超差，現在誰跟我聊核電我就跟誰吵架！"
]
all_points=[]
for text in test_data:
  points= ollama_summary_points(text)
  print(points)
  all_points.extend(points)

"""prompt 1：能執行但是沒有態度或是標籤，並且建築所產生的安全問題會被認為與核電無關  
原本的prompt  
"你是一個台灣繁體中文的內容分析助手。"  
"請針對使用者提供的文本進行重點摘要"  
"規則："  
"1. 若有重點，請簡短條列，不需做額外證據說明\n"  
"2. 若內容無意義、或純屬寒暄，請直接回覆『無重要資訊』，不要寫任何其他字眼。\n"  
"3. 每個論點之間請用『$』符號隔開，不要使用數字編號或換行。\n"    

prompt 2:可以抓到使用者情緒，但是抓太雜了，會把只有情緒也抓進來  
"你現在是一個專業的質性研究編碼員。\n"  
"請針對使用者提供的文本進行重點摘要"  
"【嚴格規則】\n"  
"1. 請抓取重點"  
"2. 輸出必須是「完整的一句話」，清楚表達出使用者對什麼事情感到什麼情緒/態度。例如：「核廢料的處理是一項極大的風險與擔憂」，絕對不可以只切成碎裂的單詞（如：核廢料、擔憂）。\n"  
"3. 不要保留口語化的廢字（如：似乎、因此、雖然），但要保留句子的完整語意。\n"  
"4. 若內容無意義、純屬寒暄、或只有單純情緒卻無具體探討的事物（例如只說「好煩」、「好擔心」），請直接回覆『無重要資訊』。\n"  
"5. 每個獨立的完整觀點之間請用『$』符號隔開，絕對不要換行、不要加上數字編號或引號。\n\n"  
"6. 純粹的情緒抒發請不要概括"  
"7. 在表現使用者態度時一切依照使用者輸入之文本為準，請勿自行增加未在該句之情緒/態度"    

prompt 3:可以結合使用者觀點，但會掉漆  
"你現在是一個專業且極度客觀的中文文本分析師。\n"
        "你的任務是從文本中精準提取使用者的「具體關注點」以及「對該關注點的態度/想法」，並將兩者融合成一個自然通順的短句。\n\n"
        "【嚴格輸出格式】\n"
        "1. 融合短句：輸出必須是高度濃縮的「一句話」（約 6~15 字），將事物與使用者的態度完美結合。例如：「是否保障人權有待商榷」、「核廢料的處置方案令人擔憂」、「重啟核四是必須的選項」。\n"
        "2. 強制拆解：若一句話包含多個不同觀點（例如同時提到優點與缺點，或因果關係），請務必拆分成多個獨立的短句。\n"
        "3. 符號分隔：每個獨立的短句之間請用『$』符號隔開，不要換行，絕對不要輸出任何欄位標題、表頭或引號。\n\n"
        "【防腦補與無效資訊過濾機制 (非常重要)】\n"
        "1. 剔除無效資訊：若文本只是純粹抱怨政府/社會（未提及具體政策）、評論問卷本身（如：問卷好長）、情緒發洩（如：我想回家、好煩）、打招呼，請一律直接且唯一回覆『無重要資訊』。\n"
        "2. 缺乏具體看法的碎片：若文本只有單一名詞而無具體看法（如：「尤其是核四」、「還有火力發電」），請直接回覆『無重要資訊』，絕對禁止自行補充未提及的資訊。\n"
        "3. 絕對忠於原意：禁止自行腦補文本中未提及的風險、優點或批判字眼。\n\n"
        "【強制輸出示範】(請絕對模仿此句型標準，不可隨意改變格式)\n"
        "輸入：現在電價一直漲，中南部又整天缺電跳電，如果核能可以提供穩定又便宜的基載電力，我認為重啟核四是必須的選項。\n"
        "輸出：電價上漲與缺電問題嚴重$核能可提供穩定便宜的電力$重啟核四是必須的選項\n"
        "輸入：我不反對使用核電，但前提是政府必須先提出一套讓全台灣人信服的核廢料最終處置方案，不然一切免談。\n"
        "輸出：不反對使用核電$核廢料最終處置方案必須先提出\n"
        "輸入：雖然核能發電不會排放溫室氣體，對減緩全球暖化有幫助，可是台灣在地震帶上，萬一發生像福島那樣的核災，我們根本承受不起。\n"
        "輸出：核能發電有助於減緩全球暖化$擔憂台灣地震帶引發嚴重核災\n"
        "輸入：反正我是絕對不會同意的啦！政府每次都騙人！\n"
        "輸出：無重要資訊\n"
        "輸入：這份問卷好長喔，填到快睡著\n"
        "輸出：無重要資訊\n"
        "輸入：我想回家\n"
        "輸出：無重要資訊\n"
        "輸入：尤其是核四\n"
        "輸出：無重要資訊\n"

開始搞計算
"""

#去重
summary_points = list(set(all_points))

target_issue="核電"
summary_points = [p for p in all_points if p != target_issue]

model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2");
issue_embedding = model.encode([target_issue])
point_embeddings = model.encode(summary_points)

#提第一列變成2D array中的一維陣列
issue_similarities = cosine_similarity(issue_embedding, point_embeddings)[0]
points_similarities = cosine_similarity(point_embeddings)

nodes = [{"id": target_issue, "size": 60, "group": 0, "relevance_score": 1.0}]
links = []
placed_points = []

#設分支節點門檻
#no_branch_threshold=0.3
branch_threshold=0.3
stop_threshold=0.7    #太相似所以停止的stop_threshold

#由小到大排序後利用[::-1]反轉
sort_issue=np.argsort(issue_similarities)[::-1]

for i in sort_issue:
  point = summary_points[i]
  sim_to_issue = issue_similarities[i]  #抓與issue的相似程度

  #預設連到target_issue
  target_node=target_issue
  link_sim = sim_to_issue
  group_id=1;

  #預設每個點最大相似度都是負無窮大
  max_sim_to_placed = float('-inf')
  best_placed = None

  #高度相似的放大圓圈
  #bigger=0;

  #找是否跟已放置節點更相似
  for place_p in placed_points:
    placed_i = summary_points.index(place_p)
    sim_to_placed = points_similarities[i,placed_i]

    if sim_to_placed > max_sim_to_placed:
      max_sim_to_placed = sim_to_placed
      best_placed = place_p
  if sim_to_issue < branch_threshold:
    print(f"🚫 剔除無關觀點：【{point}】(相似度僅 {sim_to_issue:.2f})")
    continue

  if best_placed and max_sim_to_placed > stop_threshold:
    # 找到原本那個節點，把它變大 (代表這個觀點出現頻率高)
        for node in nodes:
            if node['id'] == best_placed:
                node['size'] += 5 # 每次重複就增加 10
                break
        continue # 跳過，不重複建立節點
#    continue
  if best_placed and max_sim_to_placed > branch_threshold:
    target_node = best_placed
    link_sim = max_sim_to_placed
    group_id = 2

  visual_distance = round(float((1-link_sim)*500+50),2)

  links.append({
      "source": target_node, "sourceLabel":target_node,
      "target": point,  "targetLabel":point,
      "value": float(link_sim),
      "distance": visual_distance
  })
  nodes.append({
      "id": point,
      "size": 65,
      "group": group_id,
      #"relevance_score": float(sim_to_issue)
  })
  placed_points.append(point)

"""輸出json~~~"""

output = {
    "target_issue": target_issue,
    "nodes": nodes,
    "links": links
}
print("--- 輸出 JSON 成果 (前端視覺化用) ---")
print(json.dumps(output, ensure_ascii=False, indent=2))