# Generated by Django 6.0.4 on 2026-06-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_embedding_dim'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_user_a__82706e_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_user_b__c63718_idx',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='conv_session_number_1_or_2',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_cd68de_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
