# Generated by Django 6.0.4 on 2026-05-06 03:28

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_embedding_dim'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topic_anchor_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
