# Generated by Django 6.0.4 on 2026-05-06 13:24

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_topic_anchor_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_a_initial_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_b_initial_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.CreateModel(
            name='StanceDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift_value', models.FloatField()),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stance_drifts', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stance_drifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['measured_at'],
                'indexes': [models.Index(fields=['conversation', 'user', 'measured_at'], name='chat_stance_convers_3aa027_idx')],
            },
        ),
    ]
