# Generated by Django 6.0.4 on 2026-07-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_aisuggestion_research_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aisuggestion',
            name='chat_ais_conv_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_user_a__82706e_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_user_b__c63718_idx',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='conv_session_number_1_or_2',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_cd68de_idx',
        ),
        migrations.RemoveIndex(
            model_name='stancedrift',
            name='chat_stance_convers_3aa027_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_b',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='stancedrift',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='stancedrift',
            name='user',
        ),
        migrations.DeleteModel(
            name='AISuggestion',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='StanceDrift',
        ),
    ]
