# Generated by Django 6.0.4 on 2026-04-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(help_text='使用者的提問')),
                ('ai_response', models.TextField(blank=True, help_text='AI 的回覆', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
            ],
        ),
    ]
