"""
Django settings for BridgeUs_Django project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional during bootstrap
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: str = "") -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = _env_bool("DJANGO_DEBUG", True)

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-change-me"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false."
        )
elif not DEBUG and len(SECRET_KEY) < 32:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be at least 32 characters when "
        "DJANGO_DEBUG is false."
    )

JWT_SIGNING_KEY = os.getenv("JWT_SIGNING_KEY", SECRET_KEY)

# 給 Godot 常駐 headless server 呼叫 /api/godot/match-rooms/ 用的共用密鑰
# （不是 user JWT）。空字串 = 該端點永遠拒絕（fail closed）。見
# godot-web-deployment-spec.md §4「服務金鑰建房契約」。
GODOT_SERVICE_TOKEN = os.getenv("GODOT_SERVICE_TOKEN", "")
if not DEBUG and len(JWT_SIGNING_KEY) < 32:
    raise ImproperlyConfigured(
        "JWT_SIGNING_KEY must be at least 32 characters when "
        "DJANGO_DEBUG is false."
    )

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,0.0.0.0,dev.bridgeus.work",
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'corsheaders',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    # 改密碼／重設密碼時要作廢對方既有的 refresh token（api/token_revocation.py）。
    # 沒有這個 app，simplejwt 不會留下 OutstandingToken，舊 token 就會一直有效
    # 到自然過期為止（refresh 預設 7 天），改密碼等於防不了已外流的憑證。
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'api',
    'chat',
    'apps.summary',
]

# User model 由 accounts app 提供，接管既有 auth_user 資料表。
# 見 docs/superpowers/specs/2026-08-18-custom-user-model-design.md
AUTH_USER_MODEL = "accounts.User"

USE_REDIS_CHANNEL = _env_bool("USE_REDIS_CHANNEL", False)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BridgeUs_Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BridgeUs_Django.wsgi.application'
ASGI_APPLICATION = 'BridgeUs_Django.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").strip().lower()
if DB_ENGINE == "sqlite":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(os.getenv("SQLITE_PATH", BASE_DIR / 'db.sqlite3')),
        }
    }
elif DB_ENGINE in {"postgres", "postgresql"}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME", "bridgeus"),
            'USER': os.getenv("DB_USER", "postgres"),
            'PASSWORD': os.getenv("DB_PASSWORD", ""),
            'HOST': os.getenv("DB_HOST", "127.0.0.1"),
            'PORT': os.getenv("DB_PORT", "5432"),
            'CONN_MAX_AGE': int(os.getenv("DB_CONN_MAX_AGE", "0")),
            'CONN_HEALTH_CHECKS': _env_bool("DB_CONN_HEALTH_CHECKS", True),
        }
    }
else:
    raise ImproperlyConfigured(
        "DB_ENGINE must be one of: sqlite, postgres, postgresql."
    )

USE_REDIS_CACHE = _env_bool("USE_REDIS_CACHE", False)
REDIS_URL = os.getenv("REDIS_URL")
if USE_REDIS_CACHE:
    if not REDIS_URL:
        raise ImproperlyConfigured(
            "REDIS_URL must be set when USE_REDIS_CACHE is enabled."
        )
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'bridgeus-local-cache',
        }
    }

if USE_REDIS_CHANNEL:
    if not REDIS_URL:
        raise ImproperlyConfigured(
            "REDIS_URL must be set when USE_REDIS_CHANNEL is enabled."
        )
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

PASSWORD_MIN_LENGTH = int(os.getenv("DJANGO_PASSWORD_MIN_LENGTH", "8"))
ALLOW_COMMON_PASSWORDS = _env_bool("ALLOW_COMMON_PASSWORDS", False)
ALLOW_NUMERIC_PASSWORDS = _env_bool("ALLOW_NUMERIC_PASSWORDS", False)

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": PASSWORD_MIN_LENGTH},
    },
]

if not ALLOW_COMMON_PASSWORDS:
    AUTH_PASSWORD_VALIDATORS.append(
        {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"}
    )

if not ALLOW_NUMERIC_PASSWORDS:
    AUTH_PASSWORD_VALIDATORS.append(
        {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"}
    )


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 研究者從設定頁上傳的知識庫影片檔（VideoRecommendation.video_file）。
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 讓 DRF 預設使用 JWT 驗證
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # fail-closed：忘了寫 permission_classes 的 view 會是「需要登入」而不是
    # 「完全公開」。DRF 未設定時的預設是 AllowAny——目前每個 view 都有手動
    # 指定，但那是靠紀律維持的，開放註冊會一次新增數個 view。
    #
    # /api/token/ 與 /api/token/refresh/ 不受影響：simplejwt 的 TokenViewBase
    # 明確設了 permission_classes = ()，會壓過這裡的預設。
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 不設 DEFAULT_THROTTLE_CLASSES：限流只掛在需要的 view 上（用
    # ScopedRateThrottle + throttle_scope），不全域套用。
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('THROTTLE_LOGIN', '10/min'),
        # 60 而非個位數：DRF 對未認證請求依 IP 計數，而受試者會在同一個場地
        # 集體註冊、共用 NAT 出口 IP。5/hour 會讓第 6 位受試者開始就註冊失敗，
        # 直接毀掉一次資料收集。本平台不是公開商業服務、URL 未對外宣傳，要防的
        # 是隨機掃描而非有組織的濫用；真的遇到濫用可用環境變數即時調低。
        'register': os.getenv('THROTTLE_REGISTER', '60/hour'),
        # 驗 old_password 的端點等於一個密碼 oracle，必須限流。這個 scope 只掛在
        # 已認證的 view 上，DRF 因此依 user id 計數而不是 IP——受試者集體在同一
        # 場地共用 NAT 出口 IP，依 IP 計數會讓一個人試錯就鎖住整間教室。
        'change_password': os.getenv('THROTTLE_CHANGE_PASSWORD', '5/min'),
    },
}

SIMPLE_JWT = {
    'SIGNING_KEY': JWT_SIGNING_KEY,
    # simplejwt 預設 False，因此 /api/token/ 登入永遠不會更新 User.last_login，
    # 只有 Django Admin 的 session 登入才會。而研究者的帳號管理面板與 admin
    # 列表都在顯示這一欄——不開的話，他們看到的是永遠不動的舊值，比沒有這一欄
    # 更糟（看起來像有效資訊）。實測：2026-08-18 研究者帳號登入並操作平台，
    # 但 max(last_login) 仍停在 2026-06-03。
    'UPDATE_LAST_LOGIN': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "60"))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))
    ),
}

# 允許 React 伺服器來拿資料
CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    (
        "http://localhost:5173,"
        "http://127.0.0.1:5173,"
        "http://localhost:8080,"
        "http://127.0.0.1:8080,"
        "https://dev.bridgeus.work"
    ),
)
CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    ",".join(CORS_ALLOWED_ORIGINS),
)
