# Generated by Django 6.0.4 on 2026-07-07 07:35

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue_id', models.CharField(db_index=True, max_length=64)),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('summary_text', models.TextField(blank=True)),
                ('side_a_stance', models.CharField(blank=True, max_length=32)),
                ('side_b_stance', models.CharField(blank=True, max_length=32)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('stance_shift_magnitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dialogue_id'], name='summary_dia_dialogu_eef091_idx'), models.Index(fields=['topic_id', 'created_at'], name='summary_dia_topic_i_52f5f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewpointNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('dimension', models.CharField(db_index=True, max_length=64)),
                ('stance_direction', models.CharField(blank=True, max_length=32)),
                ('user_input_text', models.TextField()),
                ('ai_response_text', models.TextField(blank=True)),
                ('viewpoint_summary', models.TextField(blank=True)),
                ('source_message_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('composite_score', models.FloatField(blank=True, null=True)),
                ('score_detail', models.JSONField(blank=True, default=dict)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewpoints', to='summary.dialoguesummary')),
            ],
            options={
                'indexes': [models.Index(fields=['topic_id', 'dimension'], name='summary_vie_topic_i_858fbb_idx')],
            },
        ),
    ]
