# Generated by Django 6.0.4 on 2026-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_videorecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpointnode',
            name='speaker_side',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], max_length=1),
        ),
    ]
