# Generated by Django 6.0.4 on 2026-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_viewpointnode_speaker_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('topic_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
