# Generated by Django 6.0.4 on 2026-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_videorecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpointnode',
            name='review_status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '未通過')], db_index=True, default='pending', max_length=16),
        ),
    ]
