# Generated by Django 6.0.4 on 2026-08-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_alter_viewpointnode_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecommendation',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='kb_videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='videorecommendation',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
