# Generated by Django 6.0.4 on 2026-08-18 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_videorecommendation_video_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecommendation',
            name='stance_direction',
            field=models.CharField(choices=[('support', '支持'), ('neutral', '中立'), ('oppose', '反對')], default='neutral', max_length=16),
        ),
        migrations.CreateModel(
            name='VideoWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField(db_index=True)),
                ('stance_direction', models.CharField(choices=[('support', '支持'), ('neutral', '中立'), ('oppose', '反對')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_events', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='summary.videorecommendation')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'topic_id'], name='summary_vid_user_id_f7deb5_idx')],
            },
        ),
    ]
