# Generated by Django 6.0.4 on 2026-09-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_videorecommendation_stance_direction_videowatchevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecommendation',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
